(function(){
 const fcfg=window.HC_FIREBASE_CONFIG||{},pcfg=window.HC_PORTAL_CONFIG||{},ready=!!(fcfg.apiKey&&fcfg.authDomain&&pcfg.appsScriptUrl);
 const friendly=e=>{const c=String(e?.code||'');if(/invalid-credential|wrong-password|user-not-found/.test(c))return'Invalid username or password.';if(c.includes('email-already-in-use'))return'An account already exists for this email.';if(c.includes('too-many-requests'))return'Too many attempts. Please wait and try again.';return String(e?.message||e||'Something went wrong.').replace(/^Firebase:\s*/,'')};
 window.HCAuth={ready,friendly}; if(!ready)return;if(!firebase.apps.length)firebase.initializeApp(fcfg);const auth=firebase.auth();HCAuth.auth=auth;
 async function api(action,data={},secured=true){const fd=new FormData();fd.set('action',action);Object.entries(data).forEach(([k,v])=>fd.set(k,v==null?'':String(v)));if(secured){if(!auth.currentUser)throw Error('Please sign in again.');fd.set('idToken',await auth.currentUser.getIdToken(true))}let r;try{r=await fetch(pcfg.appsScriptUrl,{method:'POST',body:fd,mode:'cors',redirect:'follow',cache:'no-store'})}catch(e){throw Error('Cannot reach the Google Apps Script backend. Check deployment access and the Web App URL.')}const t=await r.text();let d;try{d=JSON.parse(t)}catch{console.error('Backend returned non-JSON response:',r.status,t.slice(0,300));throw Error('Backend is reachable but returned a non-JSON page. In Apps Script redeploy the latest code as Web app: Execute as Me, Who has access = Anyone, then update portal-config.js with that /exec URL.')}if(!d.ok)throw Error(d.error||d.message||'Request failed.');return d}HCAuth.api=api;
 const photo=async f=>{if(!f)return'';if(f.size>3*1024*1024)throw Error('Profile photo must be 3 MB or less.');if(!/^image\/(jpeg|png|webp)$/.test(f.type))throw Error('Profile photo must be JPG, PNG or WEBP.');return new Promise((res,rej)=>{const x=new FileReader();x.onload=()=>res(x.result);x.onerror=()=>rej(Error('Unable to read profile photo.'));x.readAsDataURL(f)})};
 HCAuth.signup=async form=>{const role=form.role.value,fullName=form.fullName.value.trim(),mobile=form.mobile.value.replace(/\D/g,''),email=form.email.value.trim().toLowerCase(),username=form.username.value.trim().toLowerCase(),password=form.password.value;if(!['telecaller','connector'].includes(role))throw Error('Select Telecaller or Connector.');if(!fullName)throw Error('Full name is required.');if(!/^[6-9]\d{9}$/.test(mobile))throw Error('Enter a valid 10-digit Indian mobile number.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter a valid email address.');if(!/^[a-zA-Z0-9._-]{4,30}$/.test(username))throw Error('Username must be 4–30 characters using letters, numbers, dot, underscore or hyphen.');if(password.length<12||password.length>64||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/\d/.test(password)||!/[^A-Za-z0-9]/.test(password))throw Error('Use 12–64 characters with uppercase, lowercase, number and special character.');if(password!==form.confirmPassword.value)throw Error('Passwords do not match.');if((await api('checkUsername',{username},false)).taken)throw Error('That username is already in use.');let cred;try{cred=await auth.createUserWithEmailAndPassword(email,password);const pf=form.profilePhoto.files[0];const reg=await api('registerExecutiveProfile',{role,fullName,mobile,email,username,photoData:await photo(pf),photoName:pf?.name||''});try{await cred.user.sendEmailVerification({url:new URL('executive-login.html',location.href).href})}catch(_){}await auth.signOut();const qs=new URLSearchParams({role:reg.role||role,code:reg.executiveId||'',name:fullName,username:username});location.href='signup-success.html?'+qs.toString()}catch(e){try{if(cred?.user)await cred.user.delete()}catch(_){}throw e}};
 async function sign(username,password){const r=await api('resolveUsername',{username:username.trim().toLowerCase()},false);if(!r.email)throw Error('Invalid username or password.');return auth.signInWithEmailAndPassword(r.email,password)}
 HCAuth.login=async f=>{await sign(f.username.value,f.password.value);const p=(await api('getProfile')).profile;if(p.status!=='active'){await auth.signOut();throw Error(p.status==='pending'?'Your account is pending administrator approval.':'Your account is inactive.')}location.href=p.role==='admin'?'admin-dashboard.html':'executive-dashboard.html'};
 HCAuth.adminLogin=async f=>{await sign(f.username.value,f.password.value);const p=(await api('getProfile')).profile;if(p.role!=='admin'||p.status!=='active'){await auth.signOut();throw Error('Administrator access is not authorised for this account.')}location.href='admin-dashboard.html'};
 HCAuth.guard=async o=>{o=o||{};const u=await new Promise(res=>{const off=auth.onAuthStateChanged(x=>{off();res(x)})});if(!u){location.href=o.adminOnly?'admin-login.html':'executive-login.html';return new Promise(()=>{})}try{const p=(await api('getProfile')).profile;if(p.status!=='active')throw Error('inactive');if(o.adminOnly&&p.role!=='admin'){location.href='executive-dashboard.html';return new Promise(()=>{})}return{user:u,profile:p}}catch(e){await auth.signOut();location.href=o.adminOnly?'admin-login.html':'executive-login.html';return new Promise(()=>{})}};
 HCAuth.logout=()=>auth.signOut().then(()=>location.href='login.html');HCAuth.resetPassword=e=>auth.sendPasswordResetEmail(String(e||'').trim().toLowerCase());
 HCAuth.changePassword=async(c,n,cf)=>{const u=auth.currentUser;if(!u||!u.email)throw Error('Please sign in again.');if(n!==cf)throw Error('New passwords do not match.');if(n===c)throw Error('New password must be different from your current password.');if(n.length<12||n.length>64||!/[A-Z]/.test(n)||!/[a-z]/.test(n)||!/\d/.test(n)||!/[^A-Za-z0-9]/.test(n))throw Error('Use 12–64 characters with uppercase, lowercase, number and special character.');await u.reauthenticateWithCredential(firebase.auth.EmailAuthProvider.credential(u.email,c));await u.updatePassword(n);await api('passwordChanged')};
 HCAuth.updateProfile=async({fullName,mobile,photoFile})=>{fullName=String(fullName||'').trim();mobile=String(mobile||'').replace(/\D/g,'');if(!fullName)throw Error('Full name is required.');if(!/^[6-9]\d{9}$/.test(mobile))throw Error('Enter a valid 10-digit Indian mobile number.');return(await api('updateProfile',{fullName,mobile,photoData:await photo(photoFile),photoName:photoFile?.name||''})).profile};
})();