(function(){
 const cfg=window.HC_FIREBASE_CONFIG,pcfg=window.HC_PORTAL_CONFIG;if(!cfg)throw Error('Firebase configuration is missing.');if(!firebase.apps.length)firebase.initializeApp(cfg);const auth=firebase.auth();window.HCAuth={auth,ready:true};
 const api=async(action,data={},token=true)=>{const fd=new FormData();fd.append('action',action);Object.entries(data||{}).forEach(([k,v])=>fd.append(k,v==null?'':v));if(token){if(!auth.currentUser)throw Error('Please sign in again.');fd.append('idToken',await auth.currentUser.getIdToken(true))}let r;try{r=await fetch(pcfg.appsScriptUrl,{method:'POST',body:fd,mode:'cors',redirect:'follow',cache:'no-store'})}catch(e){throw Error('Please check with support for login issue.')}const t=await r.text();let d;try{d=JSON.parse(t)}catch{console.error('Backend returned non-JSON response:',r.status,t.slice(0,300));throw Error('Please check with support for login issue.')}if(!d.ok)throw Error(d.error||d.message||'Request failed.');return d};HCAuth.api=api;
 const photo=async f=>{if(!f)return'';if(f.size>3*1024*1024)throw Error('Profile photo must be 3 MB or less.');if(!/^image\/(jpeg|png|webp)$/.test(f.type))throw Error('Profile photo must be JPG, PNG or WEBP.');return new Promise((res,rej)=>{const x=new FileReader();x.onload=()=>res(x.result);x.onerror=()=>rej(Error('Unable to read profile photo.'));x.readAsDataURL(f)})};
 HCAuth.signup=async form=>{const role=form.role.value,fullName=form.fullName.value.trim(),mobile=form.mobile.value.replace(/\D/g,''),email=form.email.value.trim().toLowerCase(),username=form.username.value.trim().toLowerCase(),password=form.password.value;if(!['telecaller','connector'].includes(role))throw Error('Select Telecaller or Connector.');if(!fullName)throw Error('Full name is required.');if(!/^[6-9]\d{9}$/.test(mobile))throw Error('Enter a valid 10-digit Indian mobile number.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter a valid email address.');if(!/^[a-zA-Z0-9._-]{4,30}$/.test(username))throw Error('Username must be 4–30 characters using letters, numbers, dot, underscore or hyphen.');if(password.length<12||password.length>64||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/\d/.test(password)||!/[^A-Za-z0-9]/.test(password))throw Error('Use 12–64 characters with uppercase, lowercase, number and special character.');if(password!==form.confirmPassword.value)throw Error('Passwords do not match.');if((await api('checkUsername',{username},false)).taken)throw Error('That username is already in use.');let cred;try{cred=await auth.createUserWithEmailAndPassword(email,password);const pf=form.profilePhoto.files[0];const reg=await api('registerExecutiveProfile',{role,fullName,mobile,email,username,photoData:await photo(pf),photoName:pf?.name||''});try{await cred.user.sendEmailVerification({url:new URL('executive-login.html',location.href).href})}catch(_){}await auth.signOut();const qs=new URLSearchParams({role:reg.role||role,code:reg.executiveId||'',name:fullName,username});location.href='signup-success.html?'+qs.toString()}catch(e){try{if(cred?.user)await cred.user.delete()}catch(_){}throw e}};
 async function sign(username,password){const r=await api('resolveUsername',{username:String(username||'').trim().toLowerCase()},false);if(!r.email)throw Error('Invalid username or password.');return auth.signInWithEmailAndPassword(r.email,password)}
 HCAuth.login=async f=>{await sign(f.username.value,f.password.value);const p=(await api('getProfile')).profile;if(p.status!=='active'){await auth.signOut();throw Error(p.status==='pending'?'Your account is pending administrator approval.':'Your account is inactive.')}sessionStorage.setItem('hcPortalLoggedIn','1');const ret=new URLSearchParams(location.search).get('return')||'',safe=/^[a-z0-9][a-z0-9._-]*\.html(?:[?#].*)?$/i.test(ret)?ret:'';location.replace(safe||(p.role==='admin'?'admin-dashboard.html':'executive-dashboard.html'))};
 HCAuth.adminLogin=async f=>{await sign(f.username.value,f.password.value);const p=(await api('getProfile')).profile;if(p.role!=='admin'||p.status!=='active'){await auth.signOut();throw Error('Administrator access is not authorised for this account.')}sessionStorage.setItem('hcPortalLoggedIn','1');const ret=new URLSearchParams(location.search).get('return')||'',safe=/^[a-z0-9][a-z0-9._-]*\.html(?:[?#].*)?$/i.test(ret)?ret:'';location.replace(safe||'admin-dashboard.html')};
 const PAGE_FEATURES={'executive-dashboard.html':'dashboard','lead-queue.html':'queue','new-lead.html':'addLead','loan-rates.html':'loanRates','government-schemes.html':'schemes','executive-profile.html':'profile','social-publisher.html':'socialPublisher','media-library.html':'mediaLibrary','campaign-manager.html':'campaignManager','ai-marketing-studio.html':'aiStudio','social-config.html':'socialConnections'};
 const ADMIN_ONLY_PAGES=new Set(['admin-dashboard.html','admin-settings.html','access-control.html','ad-manager.html','offer-creatives.html','research-lab.html']);
 HCAuth.guard=async o=>{o=o||{};const page=(location.pathname.split('/').pop()||'').toLowerCase(),loginPage=o.adminOnly||ADMIN_ONLY_PAGES.has(page)?'admin-login.html':'executive-login.html';const u=await new Promise(res=>{const off=auth.onAuthStateChanged(x=>{off();res(x)})});if(!u){location.replace(loginPage+'?return='+encodeURIComponent(page));return new Promise(()=>{})}try{const p=(await api('getProfile')).profile;if(p.status!=='active')throw Error('inactive');if((o.adminOnly||ADMIN_ONLY_PAGES.has(page))&&p.role!=='admin'){location.replace('executive-dashboard.html?access=denied');return new Promise(()=>{})}
   let access=null;try{access=await api('getAccessContext',{page});sessionStorage.setItem('hcAccessContext',JSON.stringify(access||{}))}catch(_){}
   if(p.role!=='admin'){const feature=PAGE_FEATURES[page];if(feature&&p.permissions&&p.permissions[feature]===false){location.replace('executive-dashboard.html?access=denied&feature='+encodeURIComponent(feature));return new Promise(()=>{})}
     const policies=access?.policies||[],denied=policies.some(x=>x.allow===false&&((x.scope==='page'&&(!x.key||String(x.key).toLowerCase()==='access'||String(x.key).toLowerCase()===page||String(x.page).toLowerCase()===page))||(x.scope==='role'&&String(x.key).toLowerCase()==='access')));
     if(denied){location.replace('executive-dashboard.html?access=denied&page='+encodeURIComponent(page));return new Promise(()=>{})}}
   sessionStorage.setItem('hcPortalLoggedIn','1');return{user:u,profile:p,access}
 }catch(e){try{await auth.signOut()}catch(_){}sessionStorage.removeItem('hcPortalLoggedIn');location.replace(loginPage+'?return='+encodeURIComponent(page));return new Promise(()=>{})}};
 HCAuth.logout=async()=>{try{sessionStorage.removeItem('hcGuestSession');sessionStorage.removeItem('hcAccessContext');sessionStorage.removeItem('hcPortalLoggedIn');localStorage.removeItem('hcIdleWarned');await auth.signOut()}catch(e){console.warn('Logout warning',e)}finally{location.replace('login.html?loggedout=1')}};
 HCAuth.resetPassword=e=>auth.sendPasswordResetEmail(String(e||'').trim().toLowerCase());
 HCAuth.changePassword=async(c,n,cf)=>{const u=auth.currentUser;if(!u||!u.email)throw Error('Please sign in again.');if(n!==cf)throw Error('New passwords do not match.');if(n===c)throw Error('New password must be different from your current password.');if(n.length<12||n.length>64||!/[A-Z]/.test(n)||!/[a-z]/.test(n)||!/\d/.test(n)||!/[^A-Za-z0-9]/.test(n))throw Error('Use 12–64 characters with uppercase, lowercase, number and special character.');await u.reauthenticateWithCredential(firebase.auth.EmailAuthProvider.credential(u.email,c));await u.updatePassword(n);await api('passwordChanged')};
 HCAuth.updateProfile=async({fullName,mobile,photoFile,nomineeName,nomineeRelationship,nomineeMobile,nomineeEmail})=>{fullName=String(fullName||'').trim();mobile=String(mobile||'').replace(/\D/g,'');if(!fullName)throw Error('Full name is required.');if(!/^[6-9]\d{9}$/.test(mobile))throw Error('Enter a valid 10-digit Indian mobile number.');nomineeMobile=String(nomineeMobile||'').replace(/\D/g,'');return(await api('updateProfile',{fullName,mobile,photoData:await photo(photoFile),photoName:photoFile?.name||'',nomineeName:String(nomineeName||'').trim(),nomineeRelationship:String(nomineeRelationship||'').trim(),nomineeMobile,nomineeEmail:String(nomineeEmail||'').trim()})).profile};
})();
