const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbwXcFXo-rdrcxWBqkzSWXhU_KYUShb3wwq7wNjV3bMThjHiCg7ELSoDU0cqqIj3atXZmQ/exec';
const WA='919618321100';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
const years=Array.from({length:new Date().getFullYear()-1990+1},(_,i)=>new Date().getFullYear()-i);
function phone(v){let x=String(v||'').replace(/\D/g,''); return /^[6-9]\d{9}$/.test(x)||/^\d{8,15}$/.test(x)}
function err(el,msg){el.classList.add('invalid');let x=el.parentElement.querySelector('.field-error');if(!x){x=document.createElement('small');x.className='field-error';el.parentElement.appendChild(x)}x.textContent=msg}
const f=document.getElementById('cibilForm');
const count=f?.querySelector('[name="cibilIssueCount"]'); const issueBox=document.createElement('div'); issueBox.id='cibilIssueManager'; issueBox.className='dynamic-panel'; count?.closest('.fields')?.after(issueBox);
function renderIssues(){const n=Math.max(0,Math.min(10,Number(count?.value||0)));issueBox.innerHTML=n?Array.from({length:n},(_,i)=>`<div class="issue-card"><div class="section-head"><h3>Issue ${i+1}</h3><button type="button" class="btn ghost small remove-cibil" data-index="${i}">Remove</button></div><div class="fields two"><label>Which type of loan / credit account? *<select name="issueLoanType_${i+1}" required><option value="">Select</option><option>Personal Loan</option><option>Home Loan</option><option>Business Loan</option><option>Loan Against Property</option><option>Vehicle Loan</option><option>Education Loan</option><option>Credit Card</option><option>Consumer Durable Loan</option><option>Other</option></select></label><label>What is the concern? *<select name="issueConcern_${i+1}" required><option value="">Select</option><option>Incorrect account information</option><option>Payment / overdue reporting</option><option>Settlement / write-off reporting</option><option>Account not closed / updated</option><option>Unknown account</option><option>Duplicate account</option><option>Too many enquiries</option><option>Other</option></select></label><label class="full">Briefly explain the issue *<textarea name="issueDetails_${i+1}" rows="3" maxlength="1500" required></textarea></label><label>Is there any current overdue? *<select name="issueOverdue_${i+1}" required><option value="">Select</option><option>Yes</option><option>No</option><option>Not sure</option></select></label><label>Approx. CIBIL score if known<input name="issueScore_${i+1}" type="number" min="300" max="900" step="1"></label><label>What kind of issue? *<select name="issueType_${i+1}" required><option value="">Select</option><option>Late payment / overdue</option><option>Settlement / write-off</option><option>Multiple enquiries</option><option>Incorrect account / reporting</option><option>Closed account still showing</option><option>Duplicate account</option><option>Credit-card issue</option><option>Unknown / other</option></select></label><label>Since — Year *<select name="issueYear_${i+1}" required><option value="">Year</option>${years.map(y=>`<option>${y}</option>`).join('')}</select></label><label>Since — Month *<select name="issueMonth_${i+1}" required><option value="">Month</option>${months.map(m=>`<option>${m}</option>`).join('')}</select></label></div></div>`).join('')+`<button type="button" id="addCibilIssue" class="btn ghost">+ Add another account issue</button>`:'';issueBox.querySelectorAll('.remove-cibil').forEach(b=>b.onclick=()=>{let v=Number(count.value||0);count.value=Math.max(0,v-1);renderIssues()});issueBox.querySelector('#addCibilIssue')?.addEventListener('click',()=>{let v=Number(count.value||0);if(v<10){count.value=v+1;renderIssues()}})}
count?.addEventListener('change',renderIssues); renderIssues();
if(f){f.querySelectorAll('input[name="cibilMobile"]').forEach(x=>x.addEventListener('input',()=>x.value=x.value.replace(/\D/g,'').slice(0,15)));
f.addEventListener('submit',async e=>{e.preventDefault();f.querySelectorAll('.invalid').forEach(x=>x.classList.remove('invalid'));f.querySelectorAll('.field-error').forEach(x=>x.remove());let ok=true;f.querySelectorAll('[required]').forEach(x=>{if(x.type==='checkbox'?!x.checked:!String(x.value||'').trim()){err(x,x.type==='checkbox'?'Please check the consent checkbox.':'This field is required.');ok=false}});if(f.cibilMobile.value&&!phone(f.cibilMobile.value)){err(f.cibilMobile,'Please enter a valid phone number.');ok=false}if(f.cibilEmail.value&&!/^\S+@\S+\.\S+$/.test(f.cibilEmail.value)){err(f.cibilEmail,'Email is invalid. Please enter a correct email ID.');ok=false}f.querySelectorAll('input[type=number][min][max]').forEach(x=>{if(x.value&&(Number(x.value)<Number(x.min)||Number(x.value)>Number(x.max))){err(x,'Please enter a valid number within the allowed range.');ok=false}});if(!ok){f.querySelector('.invalid')?.focus();return}const b=f.querySelector('button[type=submit]');b.disabled=true;b.textContent='Submitting…';const fd=new FormData(f);fd.set('action','cibil');fd.set('cibilIssueCount',count.value||'0');try{const r=await fetch(APPS_SCRIPT_URL,{method:'POST',body:fd});const d=await r.json();if(!d.ok)throw new Error(d.error||'Submission failed');location.href='cibil-thankyou.html?id='+encodeURIComponent(d.cibilId)+'&name='+encodeURIComponent(f.cibilName.value)+'&mobile='+encodeURIComponent(f.cibilMobile.value)}catch(e){const x=document.getElementById('cibilError');x.textContent='The CIBIL enquiry could not be submitted right now. Please try again or contact hellocustomerfirst@gmail.com.';x.classList.remove('hidden');b.disabled=false;b.textContent='Submit CIBIL Enquiry →'}})}
