(function(){
const PROTECTED={'loan-rates.html':'loanRates','government-schemes.html':'schemes'};
const FEATURE_MAP={'new-lead.html':'addLead','lead-queue.html':'queue','loan-rates.html':'loanRates','government-schemes.html':'schemes','executive-profile.html':'profile','executive-dashboard.html':'dashboard','social-publisher.html':'socialPublisher','media-library.html':'mediaLibrary','campaign-manager.html':'campaignManager','ai-marketing-studio.html':'aiStudio','social-config.html':'socialConnections','employer-checker.html':'employerChecker','lead-analysis.html':'loanAnalysis','insurance-guest.html':'insuranceGuest','insurance-leads.html':'insuranceLeads','creative-studio.html':'creativeStudio'};
function fileOf(h){return String(h||'').split('?')[0].split('#')[0].split('/').pop()}
function bindDrop(d){const b=d.querySelector('.nav-drop-btn');if(!b||b.dataset.hcBound)return;b.dataset.hcBound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();document.querySelectorAll('.nav-dropdown.open').forEach(x=>{if(x!==d)x.classList.remove('open')});d.classList.toggle('open');b.setAttribute('aria-expanded',d.classList.contains('open')?'true':'false')})}
function publicMarkup(logged){return `<a href="home.html">Home</a><div class="nav-dropdown"><button type="button" class="nav-drop-btn" aria-expanded="false">Loans ▾</button><div class="nav-dropdown-menu"><a href="personal-loan.html">Personal Loan</a><a href="home-loan.html">Home Loan</a><a href="home-loan-bt-topup.html">Home Loan BT + Top-up</a><a href="business-loan.html">Business Loan</a><a href="lap-loan.html">Loan Against Property</a><a href="vehicle-loan.html">Vehicle Loan</a><a href="education-loan.html">Education Loan</a><a href="balance-transfer.html">Balance Transfer / Consolidation</a><a href="project-funds.html">Project Funds</a></div></div><a href="offers.html">Latest Offers</a><a href="how-we-help.html">How We Help</a><a href="cibil.html">CIBIL & Credit</a><a href="stories.html">Stories</a><a href="faq.html">FAQ</a><a href="referral.html">Refer Someone</a><a class="nav-cta hc-enquiry-btn" href="index.html#eligibility">Start Enquiry</a><a class="nav-cta hc-login-btn" href="${logged?'logout.html':'login.html'}">${logged?'Logout':'Login'}</a>`}
function ensureMenuFor(n){let m=n.parentElement?.querySelector('.menu-btn');if(!m){m=document.createElement('button');m.className='menu-btn';m.type='button';m.setAttribute('aria-label','Open menu');m.setAttribute('aria-expanded','false');m.textContent='☰';n.parentElement?.insertBefore(m,n)}if(m){m.onclick=()=>{n.classList.toggle('open');m.setAttribute('aria-expanded',n.classList.contains('open')?'true':'false')}}}
function rebuildPublicNav(){if(document.body.dataset.trackingMode==='true')return;const logged=sessionStorage.getItem('hcPortalLogged In')==='1';document.querySelectorAll('header nav:not(.portal-nav)').forEach(n=>{n.innerHTML=publicMarkup(logged);n.querySelectorAll('.nav-dropdown').forEach(bindDrop);ensureMenuFor(n)})}
function addPortalPrimaryNavigation(){document.querySelectorAll('nav.portal-nav').forEach(n=>{if(n.querySelector('[data-portal-primary]'))return;const home=document.createElement('a');home.dataset.portalPrimary='1';home.href='executive-dashboard.html';home.textContent='Home';n.insertBefore(home,n.firstChild);const d=document.createElement('div');d.className='nav-dropdown portal-loans';d.dataset.portalPrimary='1';d.innerHTML='<button type="button" class="nav-drop-btn" aria-expanded="false">Loans ▾</button><div class="nav-dropdown-menu"><a href="personal-loan.html?portal=1">Personal Loan</a><a href="home-loan.html?portal=1">Home Loan</a><a href="home-loan-bt-topup.html?portal=1">Home Loan BT + Top-up</a><a href="business-loan.html?portal=1">Business Loan</a><a href="lap-loan.html?portal=1">Loan Against Property</a><a href="vehicle-loan.html?portal=1">Vehicle Loan</a><a href="education-loan.html?portal=1">Education Loan</a><a href="balance-transfer.html?portal=1">Balance Transfer / Consolidation</a><a href="project-funds.html?portal=1">Project Funds</a></div>';n.insertBefore(d,home.nextSibling);bindDrop(d)})}
function ensurePortalCoreLinks(){document.querySelectorAll('nav.portal-nav').forEach(n=>{const has=f=>[...n.querySelectorAll('a[href]')].some(a=>fileOf(a.getAttribute('href'))===f);const logout=n.querySelector('#logout,[data-hc-logout]');[['executive-profile.html','Profile'],['my-leads.html','My Leads'],['lead-queue.html','Assigned Queue'],['new-lead.html','Add Lead']].forEach(([href,label])=>{if(!has(href)){const a=document.createElement('a');a.href=href;a.textContent=label;n.insertBefore(a,logout||null)}})})}
function ensurePortalLogout(){document.querySelectorAll('nav.portal-nav').forEach(n=>{n.querySelectorAll('a[href="login.html"],a[href="admin-login.html"],a[href="executive-login.html"]').forEach(a=>a.remove());let b=n.querySelector('#logout,[data-hc-logout]');if(!b){b=document.createElement('button');b.type='button';b.id='logout';b.className='btn primary small';b.textContent='Logout';n.appendChild(b)}if(!b.dataset.hcBoundLogout){b.dataset.hcBoundLogout='1';b.addEventListener('click',()=>window.HCAuth?.logout?.())}})}
function standardizePortalNav(){document.querySelectorAll('nav.portal-nav').forEach(n=>{if(n.dataset.grouped)return;n.dataset.grouped='1';const logout=n.querySelector('#logout,[data-hc-logout]'),links=[...n.querySelectorAll(':scope > a')],by={};links.forEach(a=>by[fileOf(a.getAttribute('href'))]=a);[['Leads',['lead-queue.html','my-leads.html','new-lead.html']],['Resources',['loan-rates.html','government-schemes.html','media-library.html']],['Marketing',['social-publisher.html','campaign-manager.html','ai-marketing-studio.html','creative-studio.html','social-config.html']],['Administration',['ad-manager.html','offer-creatives.html','research-lab.html','employer-checker.html','insurance-leads.html','insurance-guest.html','access-control.html','admin-settings.html']]].forEach(([label,files])=>{const items=files.map(f=>by[f]).filter(Boolean);if(!items.length)return;const d=document.createElement('div');d.className='nav-dropdown portal-group';d.innerHTML='<button type="button" class="nav-drop-btn">'+label+' ▾</button><div class="nav-dropdown-menu"></div>';items.forEach(a=>d.querySelector('.nav-dropdown-menu').appendChild(a));n.insertBefore(d,logout||null);bindDrop(d)})})}
function ensureFullAdminNavigation(profile){if(!profile||profile.role!=='admin')return;document.querySelectorAll('nav.portal-nav').forEach(n=>{let d=n.querySelector('[data-admin-master]');if(d)return;d=document.createElement('div');d.className='nav-dropdown portal-group';d.dataset.adminMaster='1';d.innerHTML='<button type="button" class="nav-drop-btn">Administrator ▾</button><div class="nav-dropdown-menu admin-mega"><a href="admin-dashboard.html">Admin Dashboard</a><a href="my-leads.html?scope=all">All Leads</a><a href="my-leads.html?scope=unassigned">Unassigned Leads</a><a href="access-control.html">Access Control</a><a href="admin-settings.html">Settings</a><a href="media-library.html">Media Library</a><a href="offer-creatives.html">Offer Creatives</a><a href="ad-manager.html">Ad Manager</a><a href="research-lab.html">Research Lab</a><a href="employer-checker.html">Employer Checker</a><a href="insurance-leads.html">Insurance Leads</a><a href="insurance-guest.html">Insurance Guest Form</a><a href="creative-studio.html">Creative Studio</a><a href="campaign-manager.html">Campaigns</a><a href="ai-marketing-studio.html">HC AI Engine</a><a href="social-config.html">Social Integrations</a><a href="social-publisher.html">Social Publisher</a></div>';n.insertBefore(d,n.querySelector('#logout,[data-hc-logout]')||null);bindDrop(d)})}
function setPortalHomeByRole(profile){document.querySelectorAll('nav.portal-nav a[data-portal-primary]').forEach(a=>{if(a.textContent.trim()==='Home')a.href=profile&&profile.role==='admin'?'admin-dashboard.html':'executive-dashboard.html'})}
async function applyPortalPermissions(){if(!window.HCAuth?.auth)return;const u=HCAuth.auth.currentUser||await new Promise(r=>{const o=HCAuth.auth.onAuthStateChanged(x=>{o();r(x)})});if(!u)return;try{const p=HCAuth.getCachedProfile?.()||(await HCAuth.api('getProfile')).profile||{},perm=p.permissions||{};setPortalHomeByRole(p);ensureFullAdminNavigation(p);document.querySelectorAll('nav.portal-nav a[href]').forEach(a=>{const key=FEATURE_MAP[fileOf(a.getAttribute('href'))];if(key)a.hidden=p.role!=='admin'&&perm[key]!==true});}catch(_){}}
function bind(){document.querySelectorAll('.nav-dropdown').forEach(bindDrop);document.addEventListener('click',e=>{if(!e.target.closest('.nav-dropdown'))document.querySelectorAll('.nav-dropdown.open').forEach(x=>x.classList.remove('open'))},{passive:true});if(document.querySelector('.portal-nav')){document.querySelectorAll('.portal-nav').forEach(ensureMenuFor);addPortalPrimaryNavigation();ensurePortalCoreLinks();ensurePortalLogout();standardizePortalNav();applyPortalPermissions()}else rebuildPublicNav()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();window.addEventListener('pageshow',()=>{document.querySelectorAll('.nav-dropdown.open').forEach(x=>x.classList.remove('open'));document.querySelectorAll('nav.open').forEach(x=>x.classList.remove('open'));if(document.querySelector('.portal-nav'))applyPortalPermissions()});
})();
/* Revision 25: ordered administrator navigation */
(function(){
 function adminNav(){
  const nav=document.querySelector('.portal-nav'); if(!nav||!document.body.classList.contains('portal-body')) return;
  const adminHint=location.pathname.includes('admin-')||location.pathname.includes('access-control')||sessionStorage.getItem('hcRole')==='admin';
  if(!adminHint)return;
  nav.innerHTML=`<a href="home.html">Home</a><a href="admin-dashboard.html">Dashboard</a>
  <span class="hc-nav-group"><button type="button">Loans ▾</button><span><a href="personal-loan.html">Personal Loan</a><a href="home-loan.html">Home Loan</a><a href="education-loan.html">Education Loan</a><a href="business-loan.html">Business Loan</a><a href="lap-loan.html">Loan Against Property</a><a href="vehicle-loan.html">Vehicle Loan</a><a href="project-funds.html">Project Funding</a><a href="balance-transfer.html">Balance Transfer & Consolidation</a></span></span>
  <span class="hc-nav-group"><button type="button">Leads ▾</button><span><a href="my-leads.html?scope=all">All Leads</a><a href="my-leads.html?scope=mine">My Leads</a><a href="new-lead.html">Add Lead</a><a href="lead-queue.html">Assigned Queue</a><a href="my-leads.html?scope=assigned">Assigned Leads</a><a href="my-leads.html?scope=unassigned">Unassigned Leads</a><a href="insurance-leads.html">Insurance Leads</a><a href="insurance-guest.html">Insurance Guest Form</a></span></span>
  <span class="hc-nav-group"><button type="button">Marketing ▾</button><span><a href="creative-studio.html">Creative Studio</a><a href="social-publisher.html">Social Publisher</a><a href="campaign-manager.html">Campaigns</a><a href="ai-marketing-studio.html">HC AI Engine</a><a href="offer-creatives.html">Offers Creative</a><a href="content-library.html">Content Library</a><a href="research-lab.html">Research Lab</a></span></span>
  <span class="hc-nav-group"><button type="button">Resources ▾</button><span><a href="employer-checker.html">Employer Checker</a><a href="loan-rates.html">Loan Rates</a><a href="index.html#calculator">Loan Calculator</a><a href="media-library.html">Media Library</a><a href="government-schemes.html">Schemes</a></span></span>
  <span class="hc-nav-group"><button type="button">General Settings ▾</button><span><a href="ad-manager.html">Ad Manager</a><a href="access-control.html">Access Controls</a><a href="admin-settings.html">Settings</a></span></span>
  <a href="executive-profile.html">Profile</a><button class="btn primary small" id="logout">Logout</button>`;
  nav.querySelector('#logout').onclick=()=>window.HCAuth?.logout();
 }
 document.addEventListener('DOMContentLoaded',()=>setTimeout(adminNav,80));
})();
