(function(){
const PROTECTED={'loan-rates.html':'loanRates','government-schemes.html':'schemes'};
const FEATURE_MAP={'new-lead.html':'addLead','lead-queue.html':'queue','loan-rates.html':'loanRates','government-schemes.html':'schemes','executive-profile.html':'profile','executive-dashboard.html':'dashboard','social-publisher.html':'socialPublisher','media-library.html':'mediaLibrary','campaign-manager.html':'campaignManager','ai-marketing-studio.html':'aiStudio','social-config.html':'socialConnections'};
function fileOf(h){return String(h||'').split('?')[0].split('#')[0].split('/').pop()}
function bindDrop(d){const b=d.querySelector('.nav-drop-btn');if(!b||b.dataset.hcBound)return;b.dataset.hcBound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();document.querySelectorAll('.nav-dropdown.open').forEach(x=>{if(x!==d)x.classList.remove('open')});d.classList.toggle('open');b.setAttribute('aria-expanded',d.classList.contains('open')?'true':'false')})}
function publicMarkup(logged){return `<a href="home.html">Home</a><div class="nav-dropdown"><button type="button" class="nav-drop-btn" aria-expanded="false">Loans ▾</button><div class="nav-dropdown-menu"><a href="personal-loan.html">Personal Loan</a><a href="home-loan.html">Home Loan</a><a href="home-loan-bt-topup.html">Home Loan BT + Top-up</a><a href="business-loan.html">Business Loan</a><a href="lap-loan.html">Loan Against Property</a><a href="vehicle-loan.html">Vehicle Loan</a><a href="education-loan.html">Education Loan</a><a href="balance-transfer.html">Balance Transfer / Consolidation</a><a href="project-funds.html">Project Funds</a></div></div><a href="offers.html">Latest Offers</a><a href="how-we-help.html">How We Help</a><a href="cibil.html">CIBIL & Credit</a><a href="stories.html">Stories</a><a href="faq.html">FAQ</a><a href="referral.html">Refer Someone</a><a class="nav-cta hc-enquiry-btn" href="index.html#eligibility">Start Enquiry</a><a class="nav-cta hc-login-btn" href="${logged?'logout.html':'login.html'}">${logged?'Logout':'Login'}</a>`}
function ensureMenuFor(n){let m=n.parentElement?.querySelector('.menu-btn');if(!m){m=document.createElement('button');m.className='menu-btn';m.type='button';m.setAttribute('aria-label','Open menu');m.setAttribute('aria-expanded','false');m.textContent='☰';n.parentElement?.insertBefore(m,n)}if(m){m.onclick=()=>{n.classList.toggle('open');m.setAttribute('aria-expanded',n.classList.contains('open')?'true':'false')}}}
function rebuildPublicNav(){if(document.body.dataset.trackingMode==='true')return;const logged=sessionStorage.getItem('hcPortalLoggedIn')==='1';document.querySelectorAll('header nav:not(.portal-nav)').forEach(n=>{n.innerHTML=publicMarkup(logged);n.querySelectorAll('.nav-dropdown').forEach(bindDrop);ensureMenuFor(n)})}
function addPortalPublicMenu(){document.querySelectorAll('nav.portal-nav').forEach(n=>{if(n.querySelector('[data-public-menu]'))return;const d=document.createElement('div');d.className='nav-dropdown';d.dataset.publicMenu='1';d.innerHTML='<button type="button" class="nav-drop-btn">Public Site ▾</button><div class="nav-dropdown-menu">'+publicMarkup(true).replace(/<a class="nav-cta hc-login-btn"[^>]*>Logout<\/a>/,'')+'</div>';n.insertBefore(d,n.firstChild);bindDrop(d)})}
function ensurePortalLogout(){document.querySelectorAll('nav.portal-nav').forEach(n=>{n.querySelectorAll('a[href="login.html"],a[href="admin-login.html"],a[href="executive-login.html"]').forEach(a=>a.remove());let b=n.querySelector('#logout,[data-hc-logout]');if(!b){b=document.createElement('button');b.type='button';b.id='logout';b.className='btn primary small';b.textContent='Logout';n.appendChild(b)}if(!b.dataset.hcBoundLogout){b.dataset.hcBoundLogout='1';b.addEventListener('click',()=>window.HCAuth?.logout?.())}})}
function standardizePortalNav(){document.querySelectorAll('nav.portal-nav').forEach(n=>{if(n.dataset.grouped)return;n.dataset.grouped='1';const logout=n.querySelector('#logout,[data-hc-logout]'),links=[...n.querySelectorAll(':scope > a')],by={};links.forEach(a=>by[fileOf(a.getAttribute('href'))]=a);[['Leads',['lead-queue.html','my-leads.html','new-lead.html']],['Resources',['loan-rates.html','government-schemes.html','media-library.html']],['Marketing',['social-publisher.html','campaign-manager.html','ai-marketing-studio.html','social-config.html']],['Administration',['ad-manager.html','offer-creatives.html','research-lab.html','access-control.html','admin-settings.html']]].forEach(([label,files])=>{const items=files.map(f=>by[f]).filter(Boolean);if(!items.length)return;const d=document.createElement('div');d.className='nav-dropdown portal-group';d.innerHTML='<button type="button" class="nav-drop-btn">'+label+' ▾</button><div class="nav-dropdown-menu"></div>';items.forEach(a=>d.querySelector('.nav-dropdown-menu').appendChild(a));n.insertBefore(d,logout||null);bindDrop(d)})})}
async function applyPortalPermissions(){if(!window.HCAuth?.auth)return;const u=HCAuth.auth.currentUser||await new Promise(r=>{const o=HCAuth.auth.onAuthStateChanged(x=>{o();r(x)})});if(!u)return;try{const p=HCAuth.getCachedProfile?.()||(await HCAuth.api('getProfile')).profile||{},perm=p.permissions||{};document.querySelectorAll('nav.portal-nav a[href]').forEach(a=>{const key=FEATURE_MAP[fileOf(a.getAttribute('href'))];if(key)a.hidden=p.role!=='admin'&&perm[key]!==true});}catch(_){}}
function bind(){document.querySelectorAll('.nav-dropdown').forEach(bindDrop);document.addEventListener('click',e=>{if(!e.target.closest('.nav-dropdown'))document.querySelectorAll('.nav-dropdown.open').forEach(x=>x.classList.remove('open'))},{passive:true});if(document.querySelector('.portal-nav')){document.querySelectorAll('.portal-nav').forEach(ensureMenuFor);addPortalPublicMenu();ensurePortalLogout();standardizePortalNav();applyPortalPermissions()}else rebuildPublicNav()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();
})();